name: $(BuildDefinitionName)-$(SourceBranchName)-$(date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: lighthouse-ci@1
  displayName: 'lh healthcheck'
  inputs:
    command: 'healthcheck'
    targetArtifactPath: '$(Pipeline.Workspace)/s/'
    configFilePath: '$(Pipeline.Workspace)/s/lighthouserc.json'
    parameters: '--token $(LHCI_TOKEN) --githubToken $(GITHUB)'
- task: lighthouse-ci@1
  displayName: 'lh collect'
  inputs:
    command: 'collect'
    targetArtifactPath: '$(Pipeline.Workspace)/s/'
    configFilePath: '$(Pipeline.Workspace)/s/lighthouserc.json'
    parameters: '--token $(LHCI_TOKEN) --githubToken $(GITHUB)'
- task: lighthouse-ci@1
  displayName: 'lh assert'
  inputs:
    command: 'assert'
    targetArtifactPath: '$(Pipeline.Workspace)/s/'
    configFilePath: '$(Pipeline.Workspace)/s/lighthouserc.json'
    parameters: '--token $(LHCI_TOKEN) --githubToken $(GITHUB)'
  continueOnError: true  
- task: lighthouse-ci@1
  displayName: 'lh upload'
  inputs:
    command: 'upload'
    targetArtifactPath: '$(Pipeline.Workspace)/s/'
    configFilePath: '$(Pipeline.Workspace)/s/lighthouserc.json'
    parameters: '--token $(LHCI_TOKEN) --githubToken $(GITHUB)'
